### ISSUE TITLE
Letters in UPC

### ISSUE THREAD

**Issue by JMusto0223** [matusi143/MT-Kestrel#4]
Error when UPC contains letters

Error:
`Sorry, the website is experiencing problems.Error: Our query failed to execute and here is why: Query: SELECT * FROM `product` WHERE `UPC`=QUA56202 AND `LOCATION`=1 Errno: 1054 Error: Unknown column 'QUA56202' in 'where clause'`

**Comment by matusi143** [comment]
UPC values can only be numbers, the inventory system conforms to UPC-A and EAN-13 standards.  https://en.wikipedia.org/wiki/International_Article_Number

We will add verification to UPC entry fields to prevent the query of non conforming values.
